### ISSUE TITLE
ViroFlexView inside ViroARCamera doesn't behave as expected

### ISSUE THREAD

**Issue by AntoniaBe** [viromedia/viro#356] opened 2018-07-11 18:30 UTC
Hi all,

I have the following problem:

I placed an object in a scene  and also a ViroFlexView inside a ViroARCamera. This is the example code:

```         
            <ViroARCamera>
                <ViroFlexView style={styles.titleContainer}
                              width={0.25} height={0.25}
                              position={[0, 0, -1]} >
                </ViroFlexView>
            </ViroARCamera>

            <Viro3DObject
                source={require("../resources/object_flowers.vrx")}
                resources={[require('../resources/object_flowers_diffuse.png'),]}
                highAccuracyGaze={true}
                position={[0, 0, -4]}
                scale={[2, 2, 2]}
                rotation={[45, 0, 0]}
                type="VRX"
                transformBehaviors={["billboard"]}/>

```

So normally I would assume, that the ViroFlexView would be positioned in front of the object, because its z value is -1. But no matter how I try to change the value, it's always behind the object.

![screenshot_20180711-200937_virosample-ar](https://user-images.githubusercontent.com/15321778/42591973-898a97ce-8548-11e8-9644-fa4dcc35ea5e.jpg)

So am I doing something wrong or is this a bug? When I replace the ViroFlexView with a ViroImage and take the same position, it works.

**Comment by dthian** [comment] 2018-07-11 18:43
Hey @AntoniaBe, a ViroCamera is actually not designed to be parented objects - they should have no children. If needed, you can use ViroNode instead as the containers within which you can parent any number of objects.

Could you try the above, but instead not parent the flex view (placing it at the same view hierarchal level with the Viro3Dobject) and see if the issue re-occurs? 

Thanks!

**Comment by dthian** [comment] 2018-07-11 18:44
Actually scratch the above - you can add components to Cameras in Viro 2.81 - are you using the latest release?

**Comment by AntoniaBe** [comment] 2018-07-17 22:31
any updates on this one? :/

**Comment by dthian** [comment] 2018-07-17 22:33
Hey @AntoniaBe, apologies for the late reply. 
This does look like an issue within the renderer. I'll file a bug on our backlog so that we can root cause the problem (most likely an issue with rendering our flex views). 

Would this be a ship blocker for you?

**Comment by AntoniaBe** [comment] 2018-07-23 09:50
Hi @dthian , 

thanks for your reply! 
I do actually need the ViroFlexView Component inside the ARCamera. Is it possible to fix this one or is there some workaround?

Thanks!

**Comment by dthian** [comment] 2018-07-23 16:38
Hey @AntoniaBe, in the above, the main problem was that we are not correctly calculating the depth of the flex view to be placed in the scene, hence it is rendered incorrectly behind your flowerpot, when it should be in the front.

One possible mitigation is to perform the object placement yourself, manually (without parenting the object under the ViroCamera). With a simple js timer, you can grab the position in front of the timer at each timer tick / callback. 

To grab the position in front of the camera, you will need to get the camera's position, and it's forward direction. The idea is then to add the cameraPosition + cameraForwardDirection to get your final position in front of the camera. You can use [ViroScene.getCameraOrientationAsync() ](https://docs.viromedia.com/docs/viroscene) like it is done [here](https://github.com/viromedia/viro/issues/124). 

Once you have the position in front of the camera, you can simply set the position on your flexview / node that you want to be "locked" to the camera. I would **strongly** recommend using setNativeProps for this, so as to avoid state changes that could spam the js thread.

I've moved the bug up so that we can prioritize it for the next release.

**Comment by dthian** [comment] 2018-07-24 18:56
Hey @AntoniaBe which version of ViroReact are you using again in the above bug? Much thanks!

**Comment by AntoniaBe** [comment] 2018-07-24 19:06
Hi @dthian,

I'm using version 2.8.1.
And thank you very much for the advice, I will try it out!

**Comment by dthian** [comment] 2018-07-26 17:29
Hey @AntoniaBe, I've root caused the issue and have applied the fix - it should be available in our next release!

**Comment by dthian** [comment] 2018-07-26 19:42
A rough estimate would be around August 16th -20th.

**Comment by dthian** [comment] 2018-07-26 20:16
A rough estimate would be around August 16th-20th. Also please ignore the mitigation solution given above - the bug was deeper and more complicated that previously thought. Apologies for any inconvenience.

**Comment by dam00n** [comment] 2018-08-30 00:51
This has been fixed in the latest release. Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

Please reopen the issue if you are still having issues

**Closed by dam00n** 2018-08-30 00:51 UTC
