### ISSUE TITLE
How to add multiple objects to ARScene with individual properties?

### ISSUE THREAD

**Issue by empitesajith** [viromedia/viro#198] opened 2018-03-28 05:39 UTC
I tried to add multiple objects to an ARScene when I click a list item from a list. What I tried is to add a nodes depending on clicking list item to a static array and then return it inside ARScene using a helper method. That does work but I can only pinch last inserted item to the array. Then I created a separate class to render the object which I pass from the props. Problem with it is, it keeps re-rendering when I add a new object to the scene. 

Code for the 1st thing I tried

```
_getModel() {
        var modelArray = [];
        if (!this.props.arSceneNavigator.viroAppProps.displayObject || this.props.arSceneNavigator.viroAppProps.displayObjectName === undefined) {
            return;
        }

        let transformBehaviors = {};
        if (this.state.shouldBillboard) {
            transformBehaviors.transformBehaviors = this.state.shouldBillboard ? "billboardY" : [];
        }

        modelArray.push(
            <ViroNode
                visible={this.props.arSceneNavigator.viroAppProps.displayObject}
                position={this.state.objPosition}
                onDrag={() => {}}
                ref={this._setARNodeRef.bind(this)}
                scale={this.state.scale}
                rotation={this.state.rotation}
                dragType="FixedToWorld"
                key={this.props.arSceneNavigator.viroAppProps.displayObjectName}
                onClick={() => {
                    this._onClick2(this.props.arSceneNavigator.viroAppProps.displayObjectName);
                }}>

                <ViroAmbientLight color={"#aaaaaa"}/>

                <ViroSpotLight
                    innerAngle={5}
                    outerAngle={90}
                    direction={[0, -1, -.2]}
                    position={[0, 3, 1]}
                    color="#ffffff"
                    castsShadow={true}
                    ref={this._setSpotLightRef.bind(this)}/>

                <Viro3DObject
                    position={[0, this.props.arSceneNavigator.viroAppProps.yOffset, 0]}
                    source={this.props.arSceneNavigator.viroAppProps.objectSource}
                    type={this._getType(this.props.arSceneNavigator.viroAppProps.objectSource)}
                    onLoadEnd={this._onLoadEnd.bind(this)}
                    onLoadStart={this._onLoadStart.bind(this)}
                    onRotate={this._onRotate.bind(this)}
                    onPinch={this._onPinch.bind(this)}/>

                <ViroSurface
                    rotation={[-90, 0, 0]}
                    position={[0, -.001, 0]}
                    width={2.5} height={2.5}
                    arShadowReceiver={true}
                    ignoreEventHandling={true}/>

            </ViroNode>
        );
        this._getArraySortHelper(modelArray);
        let test = Array.from(ARHitClass.newArr);
        //newArr = static array
        return test;
    } 
```

Code for the 2nd thing I tried

```
_getModel2() {
        var modelArray = [];
        if (!this.props.arSceneNavigator.viroAppProps.displayObject || this.props.arSceneNavigator.viroAppProps.displayObjectName === undefined) {
            return;
        }

        let transformBehaviors = {};
        if (this.state.shouldBillboard) {
            transformBehaviors.transformBehaviors = this.state.shouldBillboard ? "billboardY" : [];
        }

        modelArray.push(
            <SingleObject
                name={this.props.arSceneNavigator.viroAppProps.displayObjectName}
                objKey={this.props.arSceneNavigator.viroAppProps.displayObjectName}
                key={this.props.arSceneNavigator.viroAppProps.displayObjectName}
                val={this.props}
                val2={this}
            />
        );

        this._getArraySortHelper(modelArray);
        let test = Array.from(ARHitClass.newArr);
        return test;
    }
```

SIngleObject =>

```
import React, {Component} from 'react';
import {Viro3DObject, ViroNode, ViroSpotLight, ViroSurface,ViroAmbientLight} from 'react-viro';

let TimerMixin = require('react-timer-mixin');

export class SingleObject extends Component{

    constructor(){
        super();
    }

    state = {
        objPosition: [0, 0, 0],
        scale: [.2, .2, .2],
        rotation: [0, 0, 0],
        shouldBillboard: true,
    };

    render(){
        const {val,val2} = this.props;
        return(
            <ViroNode
                visible={val.arSceneNavigator.viroAppProps.displayObject}
                position={this.state.objPosition}
                onDrag={() => {}}
                ref={this._setARNodeRef.bind(this)}
                scale={this.state.scale}
                rotation={this.state.rotation}
                dragType="FixedToWorld"
                key={val.arSceneNavigator.viroAppProps.displayObjectName + '+===='}
                onClick={()=>{console.log(this.props)}}>

                {/*<ViroAmbientLight color="#ffffff" intensity={200}/>*/}

                <ViroSpotLight
                    innerAngle={5}
                    outerAngle={90}
                    direction={[0, -1, -.2]}
                    position={[0, 3, 1]}
                    color="#ffffff"
                    castsShadow={true}
                    ref={this._setSpotLightRef.bind(this)}/>

                <Viro3DObject
                    position={[0, val.arSceneNavigator.viroAppProps.yOffset, 0]}
                    source={1}
                    type={this._getType(val.arSceneNavigator.viroAppProps.objectSource)}
                    onLoadEnd={this._onLoadEnd.bind(this)}
                    onLoadStart={this._onLoadStart.bind(this)}
                    onRotate={this._onRotate.bind(this)}
                    onPinch={this._onPinch.bind(this)}/>

                <Viro3DObject
                    position={[0, val.arSceneNavigator.viroAppProps.yOffset, 0]}
                    source={2}
                    type={this._getType(val.arSceneNavigator.viroAppProps.objectSource)}
                    onLoadEnd={this._onLoadEnd.bind(this)}
                    onLoadStart={this._onLoadStart.bind(this)}
                    onRotate={this._onRotate.bind(this)}
                    onPinch={this._onPinch.bind(this)}/>

                <ViroSurface
                    rotation={[-90, 0, 0]}
                    position={[0, -.001, 0]}
                    width={2.5} height={2.5}
                    arShadowReceiver={true}
                    ignoreEventHandling={true}
                />
            </ViroNode>
        );
    }

    _getType(imgPos) {
        const {val} = this.props;
        let imgArrPos = Number(imgPos) - 1;
        let locArr = val.arSceneNavigator.viroAppProps.locationArray;
        let locString = locArr[imgArrPos].toString();
        let type = locString.substring(locString.lastIndexOf('.') + 1);
        if (type === 'vrx') {
            return "VRX";
        }
        else if (type === 'obj') {
            return "OBJ";
        }
    }

    _setARNodeRef(component) {
        this.arNodeRef = component;
    }

    _setSpotLightRef(component) {
        this.spotLight = component;
    }

    _onRotate(rotateState, rotationFactor, source) {
        if (rotateState == 3) {
            this.setState({
                rotation: [this.state.rotation[0], this.state.rotation[1] + rotationFactor, this.state.rotation[2]]
            });
            return;
        }
        this.arNodeRef.setNativeProps({rotation: [this.state.rotation[0], this.state.rotation[1] + rotationFactor, this.state.rotation[2]]});
    }

    _onPinch(pinchState, scaleFactor, source) {
        var newScale = this.state.scale.map((x) => {
            return x * scaleFactor
        });

        if (pinchState == 3) {
            this.setState({
                scale: newScale
            });
            return;
        }

        this.arNodeRef.setNativeProps({scale: newScale});
        this.spotLight.setNativeProps({shadowFarZ: 6 * newScale[0]});
    }

    _onLoadStart() {
        const {val} = this.props;
        this.setState({
            shouldBillboard: true,
        });
        val.arSceneNavigator.viroAppProps._onLoadStart();
    }

    _onLoadEnd() {
        const {val,val2} = this.props;
        let arscn = val2.refs.arscene;
        arscn.getCameraOrientationAsync().then((orientation) => {
            arscn.performARHitTestWithRay(orientation.forward).then((results) => {
                this._onArHitTestResults(orientation.position, orientation.forward, results);
            })
        });
        val.arSceneNavigator.viroAppProps._onLoadEnd();
    }

    _onArHitTestResults(position, forward, results) {
        // Default position is just 1.5 meters in front of the user.
        let newPosition = [forward[0] * 1.5, forward[1] * 1.5, forward[2] * 1.5];
        let hitResultPosition = undefined;

        // Filter the hit test results based on the position.
        if (results.length > 0) {
            for (var i = 0; i < results.length; i++) {
                let result = results[i];
                if (result.type == "ExistingPlaneUsingExtent") {
                    var distance = Math.sqrt(((result.transform.position[0] - position[0]) * (result.transform.position[0] - position[0])) + ((result.transform.position[1] - position[1]) * (result.transform.position[1] - position[1])) + ((result.transform.position[2] - position[2]) * (result.transform.position[2] - position[2])));
                    if (distance > .2 && distance < 10) {
                        // If we found a plane greater than .2 and less than 10 meters away then choose it!
                        hitResultPosition = result.transform.position;
                        break;
                    }
                } else if (result.type == "FeaturePoint" && !hitResultPosition) {
                    // If we haven't found a plane and this feature point is within range, then we'll use it
                    // as the initial display point.
                    var distance = this._distance(position, result.transform.position);
                    if (distance > .2 && distance < 10) {
                        hitResultPosition = result.transform.position;
                    }
                }
            }
        }

        if (hitResultPosition) {
            newPosition = hitResultPosition;
        }

        // Set the initial placement of the object using new position from the hit test.
        this._setInitialPlacement(newPosition);
    }

    _setInitialPlacement(position) {
        this.setState({
            objPosition: position,
        });
        TimerMixin.setTimeout(() => {
            this._updateInitialRotation.bind(this)
        }, 200);
    }

    _updateInitialRotation() {
        this.arNodeRef.getTransformAsync().then((retDict) => {
            let rotation = retDict.rotation;
            let absX = Math.abs(rotation[0]);
            let absZ = Math.abs(rotation[2]);

            let yRotation = (rotation[1]);

            // If the X and Z aren't 0, then adjust the y rotation.
            if (absX > 1 && absZ > 1) {
                yRotation = 180 - (yRotation);
            }

            this.setState({
                rotation: [0, yRotation, 0],
                shouldBillboard: false,
            });
        });
    }

    _distance(vectorOne, vectorTwo) {
        var distance = Math.sqrt(((vectorTwo[0] - vectorOne[0]) * (vectorTwo[0] - vectorOne[0])) + ((vectorTwo[1] - vectorOne[1]) * (vectorTwo[1] - vectorOne[1])) + ((vectorTwo[2] - vectorOne[2]) * (vectorTwo[2] - vectorOne[2])));
        return distance;
    }
}

module.exports = SingleObject;
```

**Comment by dthian** [comment] 2018-03-29 23:29
Hi @empitesajith,

>Problem with it is, it keeps re-rendering when I add a new object to the scene.

In React Native, [state / parent state changes](http://lucybain.com/blog/2017/react-js-when-to-rerender/) will cause a re-render. As such, if there is any state changes when updating 3D objects in your main ARScene, at the scene level, this will cause the main AR scene to re-render. This is by design in React native. 

Also note that you are also setting a state in the _onPinch method that will also cause an expansive re-render for every pinch callback that is triggered (this is very costly in terms of performance). I would recommend just calling setNativeProps without any setting of state unless you absolutely need to.

**Comment by empitesajith** [comment] 2018-03-30 03:53
@dthian Thank you for your answer

Is there any proper way to add multiple objects when application is running? If you have a code sample that would be better :)

**Comment by dthian** [comment] 2018-03-30 16:30
Hey @empitesajith, actually, adding/building the scene through state changes, and then re-rendering the scene to refresh the 3D world per new object added should be fine (re-rendering is needed anyways, as you would want your scene to reflect visually the latest changes). 

When re-render occurs due to state changes, on the javascript side the render function is called, but internally on the native side (java / ios), React Native's bridge would only update those components whose properties have changed. So effectively in the end, you aren't constantly updating every single object, per frame, and there isn't a significant performance cost. The only concern was with the _onPinch code as mentioned above, since that would most likely be your perf bottle neck as it is called by the renderer and can potentially update states almost per frame. 

As such, your data array representing the property of each model (in your case a separate class and then passed in as props), that then triggers this re-render update should be fine. Using [Redux](https://redux.js.org/introduction/core-concepts) would also work as well.

**Comment by empitesajith** [comment] 2018-04-04 16:32
@dthian again thank you for your reply. If I want to make an app like your Figment AR, how can I do it? I mean how can I add multiple objects like in your Figment AR app?

**Comment by manbod** [comment] 2018-04-04 23:12
Hey @empitesajith 
Glad you reached out. I think you are on the right track 💯👍 with your second approach you pasted above. Looking at your code, I am unsure how are you calling / using `_getModel2()` in your component that renders whatever is returned from the `_getModel2()` function - is the problem that you are facing that you always see just one object? Where when the user taps on a second object from the list, it replaces the first object? If that's the case, then all you are missing might be a for loop in your function  )
Pasting gists from our Figment AR code base, that should give you a fair idea of how we structured things in the app. We do state management in the app using Redux, but excluding that in the gists below.

Our data model (static array) that contains all the 3D Objects resources and properties needed to render them correctly as below in `ModelItems.js`
```javascript
var ModelItems = [
{
    "name": "pug_animated",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_pug.png"),
    "obj": require("../res/object_pug_animated/pug_animated.vrx"),
    "materials": null,
    "animation":{name:"Take 001", delay:0, loop:true, run:true},
    "scale": [.3, .3, .3],
    "position" : [0, 0, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "spotlight_position_y": 15.2,
    "lighting_mode": "IBL",
    "resources": [require('../res/object_pug_animated/pug_body_diffuse.png'), require('../res/object_pug_animated/pug_body_normal.png'), require('../res/object_pug_animated/pug_body_specular.png')],
  },
  {
    "name": "emoji_smile",
    "selected": false,
    "loading": LoadingConstants.NONE,
    "icon_img":require("../res/icon_emoji_happy.png"),
    "obj": require("../res/emoji_smile_anim_a/emoji_smile_anim_a.vrx"),
    "materials": null,
    "animation":{name:"02", delay:0, loop:true, run:true},
    "scale": [.2, .2, .2],
    "position" : [0, .497823 + POSITION_OFFSET, 0],
    "type" : "VRX",
    "physics": undefined,
    "ref_pointer": undefined,
    "resources": [require('../res/emoji_smile_anim_a/emoji_smile_diffuse.png'), require('../res/emoji_smile_anim_a/emoji_smile_normal.png'), require('../res/emoji_smile_anim_a/emoji_smile_specular.png')],
  },
]
module.exports = {
  getModelArray: function() {
    return ModelItems;
  }
};
```
Then we have a class, we call it `ModelItemRender.js` which is almost exactly what you have in your SingleObject class up here. The key difference is going to be in your `_getModel2` and how you use it to render your objects. Pasting how we do it in Figment AR below
`figment.js`
```javascript
render: function() {
    // We get this.props.modelItems from redux
    let models = this.renderModels(this.props.modelItems);
    return (
        <ViroARScene ref="arscene" 
            onTrackingInitialized={this._onTrackingInitialized}>
            <ViroAmbientLight color="#ffffff" intensity={20}/>
          <ViroDirectionalLight color="#ffffff" direction={[0,-1,-.2]}/>
          
          <ViroSpotLight
            innerAngle={5}
            outerAngle={90}
            direction={[0,1,0]}
            position={[0, -7, 0]}
            color="#ffffff"
            intensity={250}/>
          {models}
        </ViroARScene>
    );
  },
  renderModels(modelItems) {
    var renderedObjects = [];
    if(modelItems) {
      var root = this;
      Object.keys(modelItems).forEach(function(currentKey) {
        if(modelItems[currentKey] != null && modelItems[currentKey] != undefined) {
          renderedObjects.push(
             // You SingleObject will go here instead of this object.
            <ModelItemRender key={modelItems[currentKey].uuid}
              modelIDProps={modelItems[currentKey]}
              hitTestMethod={root._performARHitTest}
              onLoadCallback={root._onLoadCallback}
              onClickStateCallback={root._onModelsClickStateCallback} />
          );
        }
      });
    }
    return renderedObjects;
  },
```
Hope this helps! The uuid and rest we do in somewhere else, but this should hopefully get you going. Good luck!

**Comment by dam00n** [comment] 2018-04-20 13:32
Closing this issue as solution has been provided. Please reopen if you have additional questions related to this topic.

**Closed by dam00n** 2018-04-20 13:32 UTC
