### ISSUE TITLE
Icon pass through Card

### ISSUE THREAD

**Issue by Zirconiumirish** [viromedia/viro#27] opened 2017-07-26 09:08 UTC
Hi, I have this type of problem do you know how I can sort it ?

Thanks
![screenshot_20170726-094856](https://user-images.githubusercontent.com/26435962/28613484-c5f12dbe-71f2-11e7-88c4-eec6b5cdf789.png)

**Comment by dthian** [comment] 2017-07-26 23:47
Hi, can you provide us the jsp html layout describing this scene? My assumption here is that you are attempting to draw an info element / image card (that has a transparency around it) in front of another fire extinguisher image card - is this right? 

This may be a depth ordering bug that had originally in our last update, and will be patched in our upcoming release. 

You might be able to get around this issue by setting applying a material on your ViroImage for the info icon with the property: readsFromDepthBuffer = false. Material properties are defined [here](http://docs.viromedia.com/docs/materials).  We are currently verifying if this is a potential mitigation and will respond back on this thread.

**Comment by Zirconiumirish** [comment] 2017-07-28 07:16
The thing is on that scene I have 2 info element close to each others and when i'm clicking on one of those my card appear but the other info element icon appear in front of the card
[Salleamanger.js.zip](https://github.com/viromedia/viro/files/1182298/Salleamanger.js.zip)



Is there maybe an order to set each elements

Here is the Javascript file 

Thanks for your help

**Comment by VikAdvani** [comment] 2017-07-29 03:56
Hi @Zirconiumirish,
Thanks for sending the code over. I was able to reproduce it. It is a bug due to the closeness of the two elements and the renderer unable to distinguish the rendering order due to that. This will be fixed in the next release, however for now I have a workaround for you.

Drop this new [InfoElement.js.zip](https://github.com/viromedia/viro/files/1184617/InfoElement.js.zip) into your app as a replacement for InfoElement. I've added two new callback properties, *onContentCardAppear* and *onContentCardHiding* and a *visible* property to it.

You can use these callbacks to hide and show the other InfoElement as the card shows, fixing the issue. 
For example your *render()* method for the infoElements would look like:
```javascript
<InfoElement content={extincteur} visible={this.state.showExtincteur}  onContentCardAppear={this._onCardAppearExtincteur} onContentCardHiding={this._onCardHideExtincteur} contentCardScale={[3.67,4,1]} position={polarToCartesian([-5, -6, 8])}/>

<InfoElement content={boitier} visible={this.state.showBoitier} onContentCardAppear={this._onCardAppearBoitier} onContentCardHiding={this._onCardHideBoitier} contentCardScale={[3.67,4,1]} position={polarToCartesian([-5, 2, 4])}/>
```
The callbacks above would be:
```javascript
    _onCardAppearExtincteur() {
        this.setState({showBoitier:false});
    },

    _onCardHideExtincteur() {
        this.setState({showBoitier:true});
    },

    _onCardAppearBoitier() {
        this.setState({showExtincteur:false});
    },

    _onCardHideBoitier() {
        this.setState({showExtincteur:true});
    },
```
Of course you'd need to add *showExtincteur* and *showBoitier* as state variables set to true to your *getInitialState*. After that the issue should be fixed! Let us know if you run into issues with this solution :)

**Comment by Zirconiumirish** [comment] 2017-07-31 08:43
Just Perfect ! Thanks for this =)

**Comment by VikAdvani** [comment] 2018-05-08 16:55
Hi @Zirconiumirish what version of Viro React and React Native are you using?

**Comment by dam00n** [comment] 2018-08-08 00:29
Closing this issue due to inactivity. If you are still experiencing issues, please re-open and provide the additional information requested. Thanks

**Closed by dam00n** 2018-08-08 00:29 UTC
