### ISSUE TITLE
[Question] Strange appearance of ViroPolyline since 2.11.0

### ISSUE THREAD

**Issue by oOMoeOo** [viromedia/viro#429] opened 2018-09-30 06:26 UTC
## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iOS 12
3. Version: ViroReact 2.11.0 and React Native 0.55.1 
4. Device(s): iPhone 7, iPhone X

## Description
Since the release of viro react 2.11.0 the appearance of all polylines has changed. It seems like the line segments are rotated and the connection points are not. Any ideas?

In the screenshot below there is a simple contour line of a polygone with a thickness of 2mm. It did never see the connection points before. Any ideas?

![img_4213](https://user-images.githubusercontent.com/5557362/46254019-1c59a200-c489-11e8-9094-6fbfa7be7361.png)

**Comment by radvani** [comment] 2018-10-01 16:11
Hi @oOMoeOo, we did make a change to polylines to fix a bug where their thickness at certain angles was going to zero. What you're showing here looks like a new regression. I'm going to take a look and see if we can fix this in our next release. Thanks for the bug report.

**Comment by dam00n** [comment] 2019-01-09 21:44
This issue was fixed in 2.12. Please let us know if you are still experiencing issues.

**Closed by dam00n** 2019-01-09 21:44 UTC
