### ISSUE TITLE
Viro3DObject position cannot fix

### ISSUE THREAD

**Issue by isurugajasinghe** [viromedia/viro#430] opened 2018-10-02 05:18 UTC
## Environment
Please provide the following information about your environment:
1. Development OS: Mac, 
2. Device OS & Version:  iOS version (11.0, 11.2) 
3. Version: ViroReact latest version and React Native 0.55.0 
4. Device(s): iPAD

## Description

When I focused to ViroARImageMarker, successfully load Viro3DObject , but Viro3DObject moving everywhere. how to fix the position related to the ViroARImageMarker image?

**Comment by tetreault** [comment] 2018-11-07 21:09
I have the opposite question @achuvm I have a 3d object of a spray can for example, that i'd love to have anchored towards the bottom of the screen so its always in view as th euser moves. Currently it stays put in its one location initially set and doesn't stay in the same location when the user moves the phone. 

```
<Viro3DObject
          source={require("./res/Metal_Bottle_With_Sprayer_Cap_Generic_fbx/Metal_Bottle_With_Sprayer_Cap_Generic.vrx")}
          scale={[0.02, 0.02, 0.02]}
          position={[0, -0.5, -0.5]}
          rotation={[-75, 0, 0]}
          type="VRX"
          materials="bottle"
        />
```

Here's an image of what I mean: 
![image from ios 2](https://user-images.githubusercontent.com/5934354/48160934-3e73ea80-e2a7-11e8-92f7-8869e5b38988.png)

But if i move my phone to the right, obviously the object is going to stay in its original location instead of staying at the bottom following along with the users camera.

**Comment by achuvm** [comment] 2018-11-07 21:37
Hi @tetreault,

Can you try tossing that object in the `<ViroCamera />` component. That should fix it relative to the camera.

Let us know if that doesn't work.

**Comment by tetreault** [comment] 2018-11-07 23:12
oh amazing thanks @achuvm ill try that tonight. thank you for the continued help :)

**Comment by tetreault** [comment] 2018-11-08 14:29
This works great @achuvm and is exactly what i needed. I'm wondering, is there any way to reduce the jitter on the 3d model when i move around with the phone? 

Here's the code I'm using: 

```javascript
<ViroARScene>
        <ViroAmbientLight color="#ffffff" />
        <ViroARCamera>
          <Viro3DObject
            source={require("./res/Metal_Bottle_With_Sprayer_Cap_Generic_fbx/Metal_Bottle_With_Sprayer_Cap_Generic.vrx")}
            scale={[0.02, 0.02, 0.02]}
            position={[0, -0.5, -0.5]}
            rotation={[-75, 0, 0]}
            type="VRX"
            materials="bottle"
          />
        </ViroARCamera>
      </ViroARScene>
```

If i keep the camera stationary for 10 seconds or so and then move around this issue does not occur. If i start the app in the testbed and immediately start moving around the 3d model jitters (but stays in the position i want it)

**Comment by tetreault** [comment] 2018-11-09 14:52
i notice there's actually a looot less jitter if I use `ViroImage` with a high res asset instead of `Viro3DObject` with a 3d model. might actually go that route instead. Would be curious  to know if there's a reason for the jitter though, i'm sure theres plenty that could cause it that i don't know about.

**Comment by dam00n** [comment] 2018-11-09 16:11
We would need to see a video of the jitter to better understand the root cause. Send one of image vs 3d object

If ARKit is not initialized (by slowly moving the device back and forth) or the rooms/area your are in has poor feature points, the tracking can be less than ideal. Lighting can also be a factor. 

See Best Practices from Apple here -> https://developer.apple.com/documentation/arkit/understanding_world_tracking_in_arkit

**Comment by tetreault** [comment] 2018-11-10 17:40
thx @dam00n for now we actually aren't going to use a 3d model, just hi-res static asset and on its other state a hi-res gif with ViroAnimatedImage. Thx for your time!

**Comment by manbod** [comment] 2018-11-19 21:55
Closing this issue. Let us know if you have any more questions / run into more issues.

**Closed by manbod** 2018-11-19 21:55 UTC

**Comment by keyserfaty** [comment] 2019-05-27 16:38
A comment just in case it helps anyone: I had this same issue and realized that changing the position of my object (x, y and z values) had an effect on this issue. When I was able to adjust these values correctly the object stopped following the camera and stayed on top of the plane.

```
 <ViroARScene onTrackingUpdated={()=>{this.setState({text : "Hello World!"})}}>
        <ViroARImageMarker target={"card"}>
            <Viro3DObject
              source={require('./res/myobject.obj')}
              scale={[.0009, .0009, .0009]}
              position={[0, 0, 0]} // <- try changing these values
              type="OBJ"
            />
        </ViroARImageMarker>
      </ViroARScene>
```
