### ISSUE TITLE
ViroText flickers when far from user

### ISSUE THREAD

**Issue by domvon** [viromedia/viro#111] opened 2017-12-11 03:25 UTC
We noticed that when a ViroText (within a ViroFlexView, in a ViroARScene) is beyond 200 (meter) from the user, the text starts flickering. And, the flickering gets worse as the distance increases. We tried various combinations of ViroFlexView scale and sizes (and font size), but we could not get rid of the flickering. When the distance was below 200, it was fine. Any idea what's going on, and how to work around this? Thanks.

**Comment by VikAdvani** [comment] 2017-12-11 23:28
Hi @domvon, we've reproduced this issue with ViroFlexView's that have a background. This seems to be an issue known as "z-fighting" where the renderer at certain distances is fighting to render either the background or text at the specified z value. 

We'll file a bug to fix this. 

To mitigate this for now, you can use the getTransformAsync method to get the position of the flexview every so often(every second or so), subtract that from the current camera position, and take the square root to get the distance. If the distance is greater X you can hide the rendering of the text, and if it's closer than X, render the flexview with the text.  X would be the distance the text begins to flicker. 

Note: There is an open bug on getTransformAsync on Android where it doesn't work. But this will be fixed in the next release.

Let me know if the above mitigation makes sense or if you have any more questions. Thanks!

**Comment by domvon** [comment] 2017-12-16 03:36
Thanks, very helpful. Based on this info, and for  anyone intersted, a workaround for this is to split the background (color or image) and text as two separate nodes, each with their own flexview, and place the text node slightly in front of the background node (poportional to the distance), and avoiding the “z-fighting” and flickering completely. Hope this helps.

**Comment by domvon** [comment] 2018-04-11 20:44
Hey team. This issue seems to be worse now with 2.5.1. The text starts to flicker when the distance is 50 meters or more (200 meters or more, earlier). Any chance this can be fixed/improved in an upcoming release? Thanks for all your great work!

**Comment by radvani** [comment] 2018-04-17 00:53
This issue has been fixed for our next release, which should be available in the next few days.

**Comment by domvon** [comment] 2018-04-19 03:33
Great, thanks guys!

**Comment by dam00n** [comment] 2018-04-20 15:39
Hi @domvon this has been fixed in the latest release, ViroReact 2.6.0

Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

Closing this issue, but please re-open if you are still encountering issues after upgrading.

**Closed by dam00n** 2018-04-20 15:39 UTC
