### ISSUE TITLE
using viro with redux ,when i pop out the ViroARSceneNavigator from the cardStack and then i try to push the ViroARSceneNavigator  into cardStack again ,the screen is black blank 

### ISSUE THREAD

**Issue by llf22282776** [viromedia/viro#196] opened 2018-03-27 13:47 UTC
Hi,@achuvm ,@dam00n 

I use redux to organize my app state ,my device is onePlus5 ,an android phone.

When i press the button in first page ,react-navigation ( a route component ) push the ViroARSceneNavigator  component into the cardStack ,then i can see the arScene in my phone screen.

After ar game ,i pop the ViroARSceneNavigator component  and goto first page 
But when i want to play ar game again (press the button again) ,the screen is black blank and the app broke in few seconds

here is the gif:

![scr_20180327_212136 mp4_2018327213608](https://user-images.githubusercontent.com/22473894/37971148-d036704c-3207-11e8-9308-88449444562a.gif)

the core code as follows:
![2](https://user-images.githubusercontent.com/22473894/37971774-5653d27c-3209-11e8-830a-1c25aad93465.jpg)
![3](https://user-images.githubusercontent.com/22473894/37971779-58ded08c-3209-11e8-873b-078752f8b10e.jpg)

i'm so confused,please give me some advices

**Comment by llf22282776** [comment] 2018-03-28 13:03
i have done  another test:
when i push ViroARSceneNavigator into navigationStack with react-navigation at first time ,the ViroARSceneNavigator  works well ,after i pop it out and try to push it into cardStack again,the camera cannot open and app broke few seconds.

"is the problem with redux or coding bugs?"
 -- i  replace the ViroARSceneNavigator  component with react native comonpents ,all component works well ,none of them occurs same problem and of course routing between pages as expected

**Comment by manbod** [comment] 2018-03-29 00:14
Hey @llf22282776 ,
Can you provide logs that include the stacktrace that you see when the app breaks? Looking at the included code screenshot we cannot tell what can be the possible root cause of the problem you are seeing.
When you run your app through the testbed -> Do you see a red screen? Or does it crash with a black screen in in testbed?
What are the contents of your `ViroARScene` (in `ARSceneSelectPage` from your code)? Is the ViroARScene also dependent on your `redux` state changes?
Pasting our documentation on [Scene Navigation](https://docs.viromedia.com/docs/scene-navigation) here. Your only difference would be using `ViroARSceneNavigator` instead of `ViroSceneNavigator` and `ViroARScene` instead of `ViroScene`

**Comment by llf22282776** [comment] 2018-03-29 02:15
@manbod ,thanks for replying !!
“Can you provide logs that include the stacktrace that you see when the app break”

-- I want to see the stacktrace too,but sadly there is no any stacktrace (no red  screen occured),when i push 
<ARManagePage> component (which render function will return <ViroArSceneNavigator />)  again,the app routes to next page successfully but the camera cannot open (so it's black and blank ,only <View> components on the screen,which is the same level with <ViroArSceneNavigator />)  and app has no responing ( the system message occurs  ),so i think it's break

" What are the contents of your ViroARScene (in ARSceneSelectPage from your code)? Is the ViroARScene also dependent on your redux state changes? "

-- in ViroARScene ,it's only the viro its own components .ViroARScene isn't dependent on redux state changes ,it receive the "state" from props passed by ViroARSceneNavigator (this.props.arSceneNavigator.viroAppProps),here is the full [code](https://github.com/llf22282776/AR_GAME)
![default](https://user-images.githubusercontent.com/22473894/38066216-a77dd02c-3339-11e8-8f2a-f49ee7929997.png)

**Comment by manbod** [comment] 2018-03-29 18:42
@llf22282776 
Sorry, we'll need more logs or information to be able to root cause your problem. Looking at your code containing viro components you seem to be doing everything correct with your viro components. Most likely the problem is not with the code in your Viro components, but somewhere else in your other components of the app. Can you debug / add logs to your redux state handling to see what could be wrong?

Some of the things that might help you in debugging your problem more / getting more information:
1. If the app breaks, you should see a stacktrace that might help in finding what could be wrong. 
2. If you don't see a stacktrace, can you add `console.log(...)` throughout your code to see where the problem is? What is the system message that you see when the app stops responding?
3. If you still don't see anything, are you building your app in debug or release? You should see lot more logs if build in debug and load your react native code via npm server on your machine.
4. Did you confirm your index == 0 when you load your ViroARSceneNavigator second time around?

**Comment by manbod** [comment] 2018-04-03 02:00
@llf22282776 
Thank you for digging into this issue in your app. This helps us understand the root cause of the problem seen by you. We've created an issue internally to fix ViroARSceneNavigator not working with react-navigation. We'll get back to you once we have a fix. 

In the meantime, is it possible for you to work around this issue? To unblock your team's app development can you structure your app's components similar to how we do in our HelloWorldScene that you get when you follow our [Quick Start Guide](https://docs.viromedia.com/docs/quick-start). You can see how the normal react native component is structured in App.js (and how it looks like in the link above at 4:33 into the video). If I understand your app correctly, it should be possible for you to render `ViroARSceneNavigator` "conditionally" depending on your redux state, without having to rely on react navigation (work around until we fix ViroReact & react navigation). Apologies for the inconvenience and the need for this work around.

**Comment by llf22282776** [comment] 2018-04-08 14:07
We find the codes that causes this problem and hope that will help you find out the reason ！
here is the code :
![1](https://user-images.githubusercontent.com/22473894/38468290-3d0d22de-3b76-11e8-80b4-7df81bc77d91.jpg)
when the tagged code exists , app always crashes after pushing it into react-navigation's stack in the second time.
but when the tagged code is removed , no matter how many times pushing  and poping action taked,the app run quite well !!!!!

**Comment by manbod** [comment] 2018-04-09 16:14
Thanks @llf22282776 ! We are looking into fixing this in an upcoming release. Thank you for sending this along.

**Comment by manbod** [comment] 2018-04-21 02:03
this has been fixed in latest release of ViroReact v2.6.0. Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

**Closed by manbod** 2018-04-21 02:03 UTC
