### ISSUE TITLE
Unable to resolve module `react-native/Libraries/StyleSheet/StyleSheetPropType

### ISSUE THREAD

**Issue by Conacious** [viromedia/viro#558] opened 2019-02-22 19:42 UTC
## Environment
Please provide the following information about your environment:
 ArchLinux kernel 4.19.23-1-lts
 Samsung Galaxy S9 Android 8.0.0
 ```
"react-native": "^0.58.5",
    "react-viro": "2.13.0"
```
## Description
Following the get started tutorial from [](https://docs.viromedia.com/docs/quick-start) on step 7 got the error that i show you on the image.

![viroerror](https://user-images.githubusercontent.com/37004512/53266800-bdb3ef80-36d9-11e9-8b6a-c81bc182498e.png)

To reproduce you just have to follow the get started tutorial. It's not working for me. Tried to solve the problem with the terminal output but didn't work. 

Thank you.

**Comment by Maxence-Machu** [comment] 2019-02-27 15:34
Same issue for us

> react-native : 0.58.5
> react-viro : 2.13.0

I temporary resolved this issue commenting the following code + each PropTypes declaration in the following components

- node_modules/react-viro/components/ViroParticleEmitter.js
- node_modules/react-viro/components/ViroImage.js
- node_modules/react-viro/components/ViroAnimatedImage.js
- node_modules/react-viro/components/ViroFlexView.js
- node_modules/react-viro/components/ViroSurface.js
- node_modules/react-viro/components/ViroButton.js
- ... (CTRL + F and search 'stylePropType'  for to find these components) 

`var StyleSheetPropType = require('react-native/Libraries/StyleSheet/StyleSheetPropType')`
`var stylePropType = StyleSheetPropType(ViroPropTypes)`

This is a workaround, consider downgrading react-native

**Comment by kaliatech** [comment] 2019-04-05 17:03
Seems these PropTypes and a few related classes were fully deprecated in recent releases of React. I think the replacement is a new package `prop-types`. More info:
 * https://reactjs.org/blog/2017/04/07/react-v15.5.0.html
 * https://github.com/facebook/prop-types

In the meantime, I noticed that stubs of the old classes were moved to `/react-native/Libraries/DeprecatedPropTypes`. So in addition @Maxence-Machu's suggestion, another short term workaround is to copy/rename the necessary classes to the correct location, or modify the source to point to the deprecated versions. After going back-and-forth I determined there's about 6 classes that have to be moved.

**Comment by kaliatech** [comment] 2019-04-05 20:58
After learning more, I think this issue can be closed as a duplicate of  #534.   Viro is not currently compatible with newer versions of React/ReactNative, and that is the reason for the missing StyleSheetPropType and similar classes.  Even after resolving these missing classes per previous comments, there are additional issues.

**Comment by VikAdvani** [comment] 2019-04-05 21:01
Hi @kaliatech, we are launching a new release shortly which will formally support React 0.59.

**Comment by jungley** [comment] 2019-04-16 16:51
@VikAdvani How soon?

**Comment by dam00n** [comment] 2019-04-16 19:25
Viro 2.14 was released last week and supports RN 0.59.3.  Release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases

**Closed by dam00n** 2019-04-16 19:25 UTC
