### ISSUE TITLE
build error: Resource entry js_arcardemo_res_tesla_object_car is already defined.

### ISSUE THREAD

**Issue by EVALIJANI** [viromedia/viro#437] opened 2018-10-12 18:19 UTC
Hi, I just cloned Viro and I have build problem with this current git version:

![image](https://user-images.githubusercontent.com/22222498/46886764-a847d280-ce68-11e8-8b94-b17bcf297b80.png)

**Comment by achuvm** [comment] 2018-10-12 18:31
Hey @EVALIJANI,

This is an issue with React Native and Android, the way React Native bundles assets in Android release builds is that they copy the assets to the Android Resources directory. The issue with that is that the Android Resources directory doesn't preserve file extensions, so if you look at the two files you have `tesla_object_car.obj` and `tesla_object_car.mtl`, you'll notice that if you drop the file extension, they'll have the exact same Resource identifier. What you can do is simply rename `tesla_object_car.obj` to `tesla_object_car_obj.obj` and use that. Also, you'll want to do a `./gradlew clean` because the first `.obj` file will have already be copied to the build directories.

Let us know if you have any other questions.

**Comment by manbod** [comment] 2018-11-19 21:48
Closing this, since it's not a bug on the platform. @EVALIJANI let us know if you have more questions.

**Closed by manbod** 2018-11-19 21:48 UTC
